#!/usr/bin/env python3
"""
build-app.py: assemble the "any mountain" web app in docs/app/ from the terrain skill's studio engine.

The six print styles and the camera live in one place, skills/procedural-terrain-art/assets/studio_template.html,
between the @@ENGINE-BEGIN and @@ENGINE-END markers. build_studio.py fills that template for one mountain; this
script copies the same code into docs/app/engine.js, wrapped in a factory so the app can build an engine for
any mountain it fetches:

    const eng = makeEngine(CFG, dem, wat);     // CFG as build_studio.py writes it, dem Float32Array (km), wat Uint8Array|null
    eng.P = {...}; eng.render(canvas, W, H, "full");

It also stamps content hashes into docs/app/index.html (?v=...) so browsers never mix an old page with a new
engine, and checks docs/app/peaks.json.

    python scripts/build-app.py            # write docs/app/engine.js and update index.html
    python scripts/build-app.py --check    # exit 1 if docs/app is out of date (CI)
"""
import argparse, hashlib, json, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATE = os.path.join(ROOT, "skills", "procedural-terrain-art", "assets", "studio_template.html")
APP = os.path.join(ROOT, "docs", "app")

HEADER = """/* engine.js: GENERATED by scripts/build-app.py from skills/procedural-terrain-art/assets/studio_template.html
   (the code between @@ENGINE-BEGIN and @@ENGINE-END). Do not edit here: change the template and run
   python scripts/build-app.py. The same code renders every studio page built by build_studio.py. */
"use strict";
function makeEngine(CFG, dem, wat){
"""
FOOTER = """
DEM = dem; WAT = wat || null;
return { CFG, PRESETS, ORDER, render, autoPanY, buildTerrain, makeScene, peaks,
  get P(){ return P; }, set P(v){ P = v; } };
}
"""


def engine_source():
    html = open(TEMPLATE, encoding="utf-8").read()
    m = re.search(r"/\* @@ENGINE-BEGIN\b.*?\*/\n(.*?)/\* @@ENGINE-END \*/\n", html, flags=re.S)
    if not m:
        sys.exit(f"{TEMPLATE}: @@ENGINE-BEGIN / @@ENGINE-END markers not found")
    body = m.group(1)
    for ph in re.findall(r"__[A-Z_]+__", body):
        sys.exit(f"engine section uses the template placeholder {ph}; keep placeholders outside the markers")
    return HEADER + body + FOOTER


def short_hash(text):
    return hashlib.sha256(text.encode("utf-8")).hexdigest()[:10]


def check_peaks(path):
    peaks = json.load(open(path, encoding="utf-8"))
    ids = set()
    for p in peaks["peaks"]:
        for k in ("id", "name", "lat", "lon", "elev", "country", "view"):
            if k not in p: sys.exit(f"peaks.json: {p.get('id', p)} lacks {k}")
        v = p["view"]
        if not all(k in v for k in ("lat", "lon", "name")): sys.exit(f"peaks.json: {p['id']} view lacks lat/lon/name")
        if p["id"] in ids: sys.exit(f"peaks.json: duplicate id {p['id']}")
        ids.add(p["id"])
        if not (-85 < p["lat"] < 85 and -180 <= p["lon"] <= 180): sys.exit(f"peaks.json: {p['id']} has bad coordinates")
    return len(ids)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="don't write; exit 1 if docs/app differs from a fresh build")
    a = ap.parse_args()
    outputs = {}
    engine = engine_source()
    outputs[os.path.join(APP, "engine.js")] = engine
    index_path = os.path.join(APP, "index.html")
    index = open(index_path, encoding="utf-8").read()
    for name in ("engine.js", "terrain.js", "app.js", "app.css"):
        src = engine if name == "engine.js" else open(os.path.join(APP, name), encoding="utf-8").read()
        pat = re.compile(r'((?:src|href)="' + re.escape(name) + r')(\?v=[0-9a-f]+)?"')
        if not pat.search(index): sys.exit(f"index.html does not reference {name}")
        index = pat.sub(lambda m: f'{m.group(1)}?v={short_hash(src)}"', index)
    outputs[index_path] = index
    n = check_peaks(os.path.join(APP, "peaks.json"))
    stale = [p for p, text in outputs.items() if not os.path.exists(p) or open(p, encoding="utf-8").read() != text]
    if a.check:
        if stale:
            print("docs/app is out of date; run python scripts/build-app.py:", *[os.path.relpath(p, ROOT) for p in stale], sep="\n  ")
            sys.exit(1)
        print(f"docs/app is up to date ({n} curated peaks)")
        return
    for p in stale:
        with open(p, "w", encoding="utf-8", newline="\n") as f: f.write(outputs[p])
    print(f"{'wrote ' + ', '.join(os.path.relpath(p, ROOT) for p in stale) if stale else 'docs/app already up to date'} ({n} curated peaks)")


if __name__ == "__main__":
    main()
